import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ChatSAT",
  description: "Generated by akshu",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <div className="flex w-full min-h-screen gap-x-[3vw] ">
          <SideBar />

          <div className="min-w-[calc{100vh-25vh}]">{children}</div>
        </div>
      </body>
    </html>
  );
}
